title: Cyber Tools
description: Cyber Research & Tools
url: "https://bsdeployment.github.io"
baseurl: "/CyberTools"

locale: "he"
direction: rtl


sass:
  style: compressed


remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

minimal_mistakes_skin: "dark"



nav:
  - title: "בית"
    url: /
  - title: "בלוג"
    url: /blog/
  - title: "אודות"
    url: /about/
