title: Cyber Tools
description: Cyber Research & Tools
url: "https://bsdeployment.github.io"
baseurl: "/CyberTools"החלף לכתובת שלך

remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "air"

navigation: main

enable_copy_code_button: true

# תצוגת ברירת מחדל לפוסטים
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      

search: true
lunr:
  search_within_pages: true
